version: '3.7'

services:

  node-exporter:
    image: prom/node-exporter:v0.18.1
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - '9100:9100'
    networks:
      - db-net
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.16.0
    command:
      - --config.file=/etc/alertmanager/config.yml
    volumes:
      - ./prometheus/rule_config.yml:/etc/alertmanager/config.yml
    ports:
      - '9093:9093'
    networks:
      - db-net
    restart: always

  prometheus:
    image: prom/prometheus:v2.10.0
    command:
      - --storage.tsdb.path=/prometheus/data
      - --config.file=/etc/prometheus/prometheus.yml
    #      - --web.console.libraries=/usr/share/prometheus/console_libraries
    #      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
      - ./prometheus/scylla_servers.yml:/etc/scylla.d/prometheus/scylla_servers.yml
      - ./prometheus/scylla_manager_servers.yml:/etc/scylla.d/prometheus/scylla_manager_servers.yml
      - ./prometheus/node_exporter_servers.yml:/etc/scylla.d/prometheus/node_exporter_servers.yml
    ports:
      - '9090:9090'
    networks:
      - db-net
    restart: always
    depends_on:
      - alertmanager
      - node-exporter

  grafana:
    image: grafana/grafana:6.3.0
    environment:
      GF_AUTH_BASIC_ENABLED: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PATHS_PROVISIONING: /var/lib/grafana/provisioning
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PANELS_DISABLE_SANITIZE_HTML: 'true'
    volumes:
      - ./grafana/build:/var/lib/grafana/dashboards:z
      - ./grafana/plugins:/var/lib/grafana/plugins:z
      - ./grafana/provisioning:/var/lib/grafana/provisioning:z
    ports:
      - '3000:3000'
    networks:
      - db-net
    depends_on:
      - prometheus
    restart: always

networks:
  db-net:
